services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ntwrk

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - ntwrk

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ntwrk

  redis-db:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - ntwrk

  car-service:
    container_name: car_sevice
    build: .
    depends_on:
      - kafka
    networks:
      - ntwrk
    ports:
      - "50051:50051"

networks:
  ntwrk:
    external: true

volumes:
  mongo_data:
  redis_data:
